#!/bin/sh
set -e
case "$1" in
    configure)
    update-rc.d -f picam defaults
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    update-rc.d -f picam remove
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
